traveler_data = {
    ('ccd250_mask_generation', 'v0') : (('fe55_analysis', 'v0'),
                                        ('bright_pixels', 'v0'),
                                        ('read_noise', 'v0'),
                                        ('dark_current', 'v0'),
                                        ('crosstalk', 'v0'),
                                        ('cte', 'v0'),
                                        ('prnu', 'v0'),
                                        ('trap', 'v0'),
                                        ('qe', 'v0'),),
    ('ts3_system_noise', 'v0') : (('read_noise', 'v0'),),
    ('ts3_system_xtalk', 'v0') : (('crosstalk', 'v0'),),
    ('ts3_fe55_data', 'v0') : (('fe55_analysis', 'v0'),
                               ('read_noise', 'v0'),),
    ('ts3_dark_files', 'v0') : (('bright_pixels', 'v0'),
                                ('dark_current', 'v0'),),
    ('ts3_spot', 'v0') : (('crosstalk', 'v0'),),
    ('ts3_superflat', 'v0') : (('cte', 'v0'),
                               ('prnu', 'v0'),),
    ('ts3_lambda', 'v0') : (('prnu', 'v0'),
                            ('qe', 'v0'),),
    ('ts3_ppump', 'v0') : (('trap', 'v0'),),
    ('fe55_analysis', 'v0') : (('bright_pixels', 'v0'),
                               ('read_noise', 'v0'),
                               ('dark_current', 'v0'),
                               ('prnu', 'v0'),
                               ('trap', 'v0'),
                               ('qe', 'v0'),),
    ('bright_pixels', 'v0') : (('read_noise', 'v0'),
                               ('dark_current', 'v0'),
                               ('crosstalk', 'v0'),
                               ('cte', 'v0'),
                               ('prnu', 'v0'),
                               ('trap', 'v0'),
                               ('qe', 'v0'),),
    ('read_noise', 'v0') : (),
    ('dark_current', 'v0') : (),
    ('crosstalk', 'v0') : (),
    ('cte', 'v0') : (),
    ('prnu', 'v0') : (),
    ('trap', 'v0') : (),
    ('qe', 'v0') : (),
    }

if __name__ == '__main__':
    from my_fakelims import FakeTraveler
    foo = FakeTraveler(traveler_data=ts3_traveler)
    print foo
